### ISSUE TITLE
Doesn't work with rxvt on linux

### ISSUE THREAD

**Issue by qux42** [sburlyaev/IDEA-Native-Terminal-Plugin#10]
Hello,

I'm using rxvt (urxvtc). Setting it as an Favorite Terminal works, but it is always open at the wrong path and not at the ProjectPath.

Is there a way to fix that?

Correct command would be in my case: 

`urxvtc -cd ${PROJECT_PATH} &`

Thanks for your help.

**Comment by sburlyaev** [comment]
Hi,
rxvt currently is not supported. I'm going to add this in the next release.
Thanks!

**Comment by sburlyaev** [comment]
@qux42 ,
The version 0.2.2 has been submitted for moderation. The updated plugin will be available within two days.
Thank you for your request.
