### ISSUE TITLE
Support bash on Windows 10 (WSL)

### ISSUE THREAD

**Issue by petervandenbroek** [sburlyaev/IDEA-Native-Terminal-Plugin#14]
Configuring bash.exe in Windows 10 (with the embedded Ubuntu installed) works fine and it opens the terminal as expected.

However, the folder it opens isn't the project directory, but the IDE bin folder.
For example, in GoLand this is: "/mnt/c/Program Files/JetBrains/GoLand 2018.2.4/bin

**Comment by sburlyaev** [comment]
Hi Peter, I will check. Thanks!

**Comment by sburlyaev** [comment]
Could you please send the IDE log or your "Favorite terminal" line?

**Comment by petervandenbroek** [comment]
Favorite Terminal: "bash.exe"
The Ubuntu terminal lives in system32, so can be called the same way as cmd and powershell.

Relevant IDE log lines:
```
2018-11-16 16:14:17,626 [24995736]   INFO - m.sburlyaev.cmd.plugin.OpenCmd - Environment{os=WINDOWS, osVersion='10.0', gui='windows'}
2018-11-16 16:14:17,627 [24995737]   INFO - yaev.cmd.plugin.CommandBuilder - Favorite terminal is [bash.exe] and using [GENERIC]
2018-11-16 16:14:17,627 [24995737]   INFO - m.sburlyaev.cmd.plugin.OpenCmd - [cmd, /c, start, bash.exe]
```

**Comment by sburlyaev** [comment]
Hi @petervandenbroek ,
I have added support for bash (with WSL) and it will be available in a few days.
Thanks for the request!

**Comment by petervandenbroek** [comment]
Awesome, I can confirm it works as expected.

Thanks for the quick fix!

**Comment by G-Rath** [comment]
@sburlyaev was this ever released? I'm using v0.4.1 from the jetbrains plugins store, and am having this issue.

**Comment by sburlyaev** [comment]
Hi @G-Rath,

Could you share more details? Your command line, project directory, plugin log messages, etc.

**Comment by G-Rath** [comment]
@sburlyaev Sure can! I had intended to added that info, but didn't get the time.

I'm running Windows 10, using WSLv1.

I've tried with a number of commands:

```
wsl
wsl ${project_directory}
wsl 'bash -c "cd $(wslpath "${project.dir}"); $SHELL"'
```

My log outputs are:

```
2019-10-06 19:53:13,149 [45748725]   INFO - actions.OpenTerminalBaseAction - [cmd, /c, start, wsl] 
2019-10-06 19:55:51,428 [45907004]   INFO - actions.OpenTerminalBaseAction - [wsl, C:/Users/G-Rath/workspace/personal-projects/bitbucket-watcher-lambda]
2019-10-06 19:56:56,195 [45971771]   INFO - actions.OpenTerminalBaseAction - [wsl, 'bash, -c, "cd, $(wslpath, "C:/Users/G-Rath/workspace/personal-projects/bitbucket-watcher-lambda");, $SHELL"']
```

The issue is twofold from what I can tell: firstly, paths are not being translated to WSL paths, meaning that WSL exists w/ "No such directory", and then spaces are being replaced with ", ", making the commands invalid.

**Comment by sburlyaev** [comment]
I can recommend to try `bash` or `bash.exe`, or full path to that.
As I remember, it does not handle `wsl` as a shortcut.

**Comment by G-Rath** [comment]
> I can recommend to try bash or bash.exe, or full path to that.

Just FYI MS recommend using `wsl.exe`:

> The best way to interact with the Windows Subsystem for Linux is to use the wsl.exe command.

*But* `bash.exe` isn't deprecated, so it should serve in the meantime :)

**Comment by sburlyaev** [comment]
Sound reasonable. I will add `wsl` to known WSL keywords.
Thank you!
