### ISSUE TITLE
Add "Open in Terminal"-alike functionality

### ISSUE THREAD

**Issue by friek** [sburlyaev/IDEA-Native-Terminal-Plugin#19]
I was wondering if, instead of (or in addition to) adding the icon to the main toolbar, it is possible to add functionality to open the configured terminal in a selected directory instead of the configured directory.

It'd basically be the same as the default "Open in Terminal" functionality built into the Jetbrains IDEs. The goal would be to mimic that same functionality, but then with your plugin.

Thanks.

**Comment by sburlyaev** [comment]
Hi @friek,

It's done ; ) The update will be available in a few days.
I didn't do much testing with it, so be careful : )

Thanks for the great idea!

**Comment by friek** [comment]
Just installed the update in IntelliJ and it's working perfectly 👍 
Thanks again 💯 🥇
