### ISSUE TITLE
is it possible to support cmder?

### ISSUE THREAD

**Issue by darklonely** [sburlyaev/IDEA-Native-Terminal-Plugin#21]
hello :), is it possible to support cmder?

**Comment by sburlyaev** [comment]
Hi @darklonely,

I think yes, will look into it tomorrow.

Thanks!

**Comment by sburlyaev** [comment]
Hi @darklonely,
Added for 0.3.1 - it will be available in a few days.

Thanks.

**Comment by sburlyaev** [comment]
Awesome terminal, btw. Thanks!

**Comment by darklonely** [comment]
:) yes, i think it's better than ConEmu.
Unfortunately the `cmder.exe /start d:/xxx` command is not working for me in Windows 7 x64.
I tested the `cmder.exe /task cmder d:/xxx` command which is working as expected.

**Comment by sburlyaev** [comment]
Oh, thanks. Will fix.

**Comment by darklonely** [comment]
since Windows 10 2019 May just released, i changed to it from windows 7(not update, a total fresh install).
the cmder.exe /start d:/xxx command is still not working as expected.
instead, the cmder.exe /task cmder d:/xxx command is fun.
i don't know why, any tips?

**Comment by sburlyaev** [comment]
> single instance mode of Cmder

Probably, it's the reason. Does the `/task` command work for you?

**Comment by darklonely** [comment]
yes. the `cmder.exe /task cmder d:/xxx` command works

**Comment by sburlyaev** [comment]
:+1: I think, we can use this command for all Windows OS-s.

**Comment by sburlyaev** [comment]
Fixed that. Thanks for the advice!
