### ISSUE TITLE
Feature request: open external terminal from editor popup menu

### ISSUE THREAD

**Issue by K4zuki** [sburlyaev/IDEA-Native-Terminal-Plugin#22]
Is it possible to open terminal on in directory of the file editing?

### Goal of my request:
When editing `C:\workspace\text.txt`, start terminal via editor popup menu like this
<img width="250" alt="editor-popup-menu" src="https://user-images.githubusercontent.com/9379328/53169763-808c2680-3621-11e9-98da-c210f8926793.png">

and terminal is `cd` 'd to `C:\workspace` (or just `$PWD` for the file)

---

The screenshot above is achieved by simply adding
`<add-to-group group-id="EditorPopupMenu" anchor="after" relative-to-action="EditorPopupMenu"/>
`
into `plugin.xml` around L34 but I am not sure if this is a correct way...

**Comment by sburlyaev** [comment]
Hi @K4zuki,

Yep, it's possible. I will add this feature to the next version.

Thanks for the request!

**Comment by K4zuki** [comment]
@sburlyaev Update is confirmed as requested. Thanks!
