### ISSUE TITLE
Allow opening a terminal while indexing the project

### ISSUE THREAD

**Issue by m1r0** [sburlyaev/IDEA-Native-Terminal-Plugin#24]
Just a quick suggestion: it would be nice to have the ability to open the terminal right away and not wait for the project to index.

![vaMajuc](https://user-images.githubusercontent.com/1612178/54911176-8f9f1680-4ef6-11e9-865e-d55260120874.png)

Thanks for the plugin!

**Comment by sburlyaev** [comment]
Thanks Miroslav,

Good point, but actually I'm not really sure if it's even possible. Will look into it one more time.

Thanks!

**Comment by sburlyaev** [comment]
Hi @m1r0 ,

I've just found a solution! It will be fixed in the next release.

Thanks!

**Comment by m1r0** [comment]
Thanks @sburlyaev!
