### ISSUE TITLE
Nothing changes after plugin installation 

### ISSUE THREAD

**Issue by Sammers21** [sburlyaev/IDEA-Native-Terminal-Plugin#25]
### Env
```bash
$ uname -a
Linux device 5.0.17-300.fc30.x86_64 #1 SMP Mon May 20 15:36:26 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

idea ultimate version: `191.6707.61` or, shortly, `2019.1.2`
native terminal version: `0.3.5`
os: Fedora 30 with 
```bash
$ gnome-shell --version
GNOME Shell 3.32.2
```

### Problem

After plugin installation, nothing changes. Even with manual shell path setup. 

![image](https://user-images.githubusercontent.com/16746106/58477873-520c7300-815d-11e9-8562-3310fcac7f1e.png)

![image](https://user-images.githubusercontent.com/16746106/58477884-59338100-815d-11e9-80e2-6aab4f662935.png)

**Comment by sburlyaev** [comment]
Hi @Sammers21,
`zsh` is not supported yet. I will add it in the future release.
Thanks!

**Comment by sburlyaev** [comment]
Hi @Sammers21,
Could you please share more information about how you run zsh shell outside IDE?
Is it your default shell?

**Comment by Sammers21** [comment]
@sburlyaev, Yes, it is.

**Comment by sburlyaev** [comment]
what terminal do you use?

**Comment by sburlyaev** [comment]
Hey @Sammers21 !

Have you already tried the latest version with `${project.dir}` in your command? Does it work for you?

**Comment by Sammers21** [comment]
@sburlyaev, it does work well
