### ISSUE TITLE
Wish for more termial type

### ISSUE THREAD

**Issue by cedarwu** [sburlyaev/IDEA-Native-Terminal-Plugin#26]
After wsl on windows appears, more and more terminal runs on windows, such as https://hyper.is/ .
Wish your plugin can support more terminal type or  just run unknown terminal with current path as param.
Currently, if I select unknown terminal, this plugin only start the terminal with no params, which is not desired behaviour.
Thank you for your plugin.

**Comment by sburlyaev** [comment]
Hi @cedarwu,
Sounds reasonable.
I have been thinking about it for some time, and the main argument against this solution was to make the plugin as simple as I can. But it is nearly impossible to support all bunch of shells and terminals we have today and that will be launched in a future.
So, I guess, it is a good solution to add a possibility for advanced users to specify any command they want and just inject the project directory into it.
Thanks!

**Comment by cedarwu** [comment]
Your idea is more reasonable and efficient.
That would be perfect if users can customize the command with project directory.
I look forward to it.

**Comment by sburlyaev** [comment]
Hey @cedarwu !

Have you already tried to specify `hyper ${project.dir}` on yours?

**Comment by pelepelin** [comment]
What is the resolution? I've just tried `C:/Users/User/Desktop/test.bat ${project.dir}` and it does not start the batch file. With `C:/Users/User/Desktop/test.bat` the batch file is started without parameters.

**Comment by sburlyaev** [comment]
@pelepelin can you attach your execution log line?

**Comment by sburlyaev** [comment]
@pelepelin https://intellij-support.jetbrains.com/hc/en-us/articles/207241085-Locating-IDE-log-files

I'm interested in some lines which contain
'OpenTerminalBaseAction'.

**Comment by pelepelin** [comment]
When the line in the config is `C:/Users/User/Desktop/test.bat ${project.dir}` a console window does not open and the lines in the log are
```
2020-01-08 13:03:17,687 [ 221060]   INFO - actions.OpenTerminalBaseAction - Environment{os=WINDOWS, osVersion='10.0', gui='windows'} 
2020-01-08 13:03:17,688 [ 221061]   INFO - actions.OpenTerminalBaseAction - [C:/Users/User/Desktop/test.bat, C:/Users/User/dev/tmp/express-generated] 
```

When the line in the config is `C:/Users/User/Desktop/test.bat` a console window is open with lines
```

C:\Program Files\JetBrains\PhpStorm 2019\jbr\bin>echo
Режим вывода команд на экран (ECHO) включен.

C:\Program Files\JetBrains\PhpStorm 2019\jbr\bin>pause
Для продолжения нажмите любую клавишу . . .
```
and lines in the log are

```
2020-01-08 13:08:43,691 [ 547064]   INFO - actions.OpenTerminalBaseAction - Environment{os=WINDOWS, osVersion='10.0', gui='windows'} 
2020-01-08 13:08:43,692 [ 547065]   INFO - yaev.cmd.plugin.CommandBuilder - Favorite terminal is [C:/Users/User/Desktop/test.bat] and using [GENERIC] 
2020-01-08 13:08:43,693 [ 547066]   INFO - actions.OpenTerminalBaseAction - [cmd, /c, start, C:/Users/User/Desktop/test.bat] 
```

The `test.bat` is
```
echo %*
pause
```

**Comment by pelepelin** [comment]
It seems config line `cmd /c start C:/Users/User/Desktop/test.bat  ${project.dir}` works as intended

```

C:\Program Files\JetBrains\PhpStorm 2019\jbr\bin>echo C:/Users/User/dev/tmp/express-generated
C:/Users/User/dev/tmp/express-generated

C:\Program Files\JetBrains\PhpStorm 2019\jbr\bin>pause
Для продолжения нажмите любую клавишу . . .
```

Except that I need this window to close after a real terminal app will be started.

**Comment by sburlyaev** [comment]
@pelepelin I don't really understand your use case.

What do you mean by `real terminal`? Do you want to run another terminal app?

**Comment by pelepelin** [comment]
I'm trying to use [wsltty](https://github.com/mintty/wsltty), which is normally started by a batch file. Of course I should be able to extract the actual arguments to `.exe` file from the script, but starting the `.bat` should have been as easy as 
```
cd %1
wsl.bat
```

**Comment by pelepelin** [comment]
So, for my case I've found a workaround like this.

Create a `test.bat`:
```
cd %1
wsl.bat
```

Create a Windows "shortcut" `test.lnk`:
- object: `C:\Users\User\Desktop\test.bat`
- window: minimized (reduces visible flicker)

Point the plugin to this shortcut with line:
`cmd /c start C:/Users/User/Desktop/test.lnk ${project.dir}`

**Comment by sburlyaev** [comment]
Thank you Konstantin!
