### ISSUE TITLE
Subdirectory setting is global, rather than per project

### ISSUE THREAD

**Issue by jeffmath** [sburlyaev/IDEA-Native-Terminal-Plugin#27]
When this setting is changed for one project, it is changed for all projects.  This makes the setting more of an annoyance than a benefit, as I have to change its value as I bounce from project to project in the IDE.

**Comment by sburlyaev** [comment]
Hi @jeffmath,

Good point. Probably, I should remove this because now you can simply use a context menu to open the terminal by pressing the right button on any folder/file and then select "Open in external terminal".
Thanks!

**Comment by jeffmath** [comment]
@sburlyaev May I ask, how much would you charge for your development time to make the setting be per project?

**Comment by sburlyaev** [comment]
Oh, it is always free 🙂
I'll try to look into it tomorrow.

**Comment by jeffmath** [comment]
Thanks so much, Sergey!  I use your plugin every day for my work, even more so ever since WebStorm's internal terminal has been giving me problems.

**Comment by sburlyaev** [comment]
Hi @jeffmath ,

Looks like there is no straightforward way do this. But I have some ideas about how to deal with it:
- IntelliJ API provides a list of open projects, so I can add a dropdown menu with these projects to the _subdirectory_ setting item. Thus, it will be possible to specify a subdirectory for a selected project.
- Another way, add a context menu item - "_Set as the default directory for external terminal_". Then, we can click on any project folder and set it as default, so it will be opened by the terminal button.

Which of the above options do you find more convenient?

**Comment by jeffmath** [comment]
@sburlyaev, that second option sounds fantastic, as long as a different folder may be selected (and remembered) for each project.

**Comment by sburlyaev** [comment]
Yes, it will be stored in a _project-level_  `PropertiesComponent`. Ok, will go this way. Thanks!

**Comment by jeffmath** [comment]
Thank you, Sergey!

**Comment by sburlyaev** [comment]
### Hi Jeff!

I uploaded a new build here: https://plugins.jetbrains.com/plugin/9966-native-terminal/versions
under **EAP** button - version `0.4.1`. So, you can download and install it manually via _IDE plugins settings_ ("Install Plugin from Disk").

Unfortunately, I had no time to do much testing with it but it's very welcome to hear any feedback from you.
Thanks!

**Comment by jeffmath** [comment]
Works like a charm, @sburlyaev.  Great job!

**Comment by sburlyaev** [comment]
Glad to hear that. Thank you!
