### ISSUE TITLE
Button does not appear in redesigned toolbar

### ISSUE THREAD

**Issue by andgeno** [sburlyaev/IDEA-Native-Terminal-Plugin#36]
The toolbar was redesigned in a recent update which seems to have broken this plugin half-way. The shortcut button in the toolbar is no longer visible.

One can still choose to switch back to the previous design via `View | Appearance | Toolbar Classic` but that is more of a workaround than a real fix.

Would be nice to have the button also appear on the redesigned toolbar.

**Comment by sburlyaev** [comment]
Hi @andgeno, thanks for letting me know.
Could you give some details on what IDE / version you are using to check this out?

**Comment by andgeno** [comment]
Sure, it's `Rider for Unreal Engine`. Build: `#RDCPPP-213.5744.303, built on December 10, 2021`.

**Comment by sburlyaev** [comment]
A new build (v0.4.5) has been uploaded to JetBrains Marketplace - it will be available for download soon. Thanks!
