### ISSUE TITLE
I need subdirectory in my laravel projects

### ISSUE THREAD

**Issue by homayoonahmadi** [sburlyaev/IDEA-Native-Terminal-Plugin#38]
Hi there, can you enable subdirectory option in project settings please? I have separated public_html directory from other project directories and I have to move inside laravel directory everytime I open cmder using `cd` command. I'm using PhpStorm

here is my project structure:

laravel-project
                     |
                     |---- .idea
                     |---- laravel
                     |---- public_html

**Comment by sburlyaev** [comment]
Hi @homayoonahmadi, I would suggest to try setting this directory as a default - right click on that directory, then “Set as Default Directory for External Terminal”.
