### ISSUE TITLE
Save terminal tabs between sessions 

### ISSUE THREAD

**Issue by billmetangmo** [sburlyaev/IDEA-Native-Terminal-Plugin#4]
Hello @sburlyaev 

I searched on github for a idea terminal plugin that implements https://youtrack.jetbrains.com/issue/IDEA-117946#u=1467737379896 like this https://youtrack.jetbrains.com/issue/IDEA-134884 for example. I did not find it but I found yours.

Do you think, it will be possible to implement it easily in your project or if it's hard i can provide help and/or ask also help to the IntellijDea thread.

Regards

**Comment by sburlyaev** [comment]
Hi @billmetangmo ,
my plugin is not an implementation of terminal itself - it just invokes a prefered terminal from your PC (e.g. Command Prompt, GitBash, iTerm). It is not linked to specific project, it is just another window in your OS.
So, you need to contact JetBrains team to move it forward.
 
Regards.

**Comment by billmetangmo** [comment]
Oki. Thanks very much for your response :)

**Comment by sburlyaev** [comment]
:thumbsup: You are welcome!
