### ISSUE TITLE
No terminal button in the New UI (2022.3)

### ISSUE THREAD

**Issue by maicol07** [sburlyaev/IDEA-Native-Terminal-Plugin#40]
Since the quick actions toolbar isn't there anymore in the new UI, the terminal button isn't visible anymore.

**Comment by sburlyaev** [comment]
Hi Maicol,
Could you tell me more about IDEs where you're facing this issue?
Thank you

**Comment by maicol07** [comment]
Basically, all Jetbrains IDEs when you have the new UI enabled!

**Comment by sburlyaev** [comment]
Hm, `IntelliJ IDEA 2022.2 (Build #IU-222.3345.118, built on July 26, 2022)` looks ok to me.
What should I turn on to reproduce this?

**Comment by sburlyaev** [comment]
As I understand it will be a part of 2022.3 EAP: https://blog.jetbrains.com/idea/2022/05/take-part-in-the-new-ui-preview-for-your-jetbrains-ide/. Will take a look at this.
Thank you

**Comment by maicol07** [comment]
Yes, when 2022.3 will be released the new UI will be shipped as the default UI (with the option to go back to the old one). On 2022.2 you can try the new UI with that plugin
