### ISSUE TITLE
Terminal opens in sub-directory instead of project directory

### ISSUE THREAD

**Issue by ChrisJan00** [sburlyaev/IDEA-Native-Terminal-Plugin#42]
Android Studio Flamingo | 2022.2.1 Patch 1
Native Terminal Plugin v0.4.6.
OS: Linux Mint 21.1 Cinnamon
Terminal: gnome-terminal 3.44.0

I have been using the Native Terminal plugin for years. Click on the icon, opens a new terminal window in the project directory. Great.

Since the last update of Android Studio (from Electric Eel to Flamingo), when a new terminal window is open, it starts in one subdirectory of the project ( $projectdir/app/src/main/java/com/myexample/somepackage ), which means every time I have to type "cd .. cd .. cd .." several times to go all the way up.  I don't remember if the terminal plugin was also updated since then (meaning, it's not clear if it's the Android Studio update that caused this, or the Terminal Plugin itself).  I could not find any options or setting to modify, to make it behave like it used to.

Is there a way to fix this? Like, a cache to be deleted somewhere, or a setting to modify?

**Comment by sburlyaev** [comment]
Hi Chris, 

I would suggest trying to change the default project directory for the plugin:
- Press the right button on your application root directory in the Project tab.
- And then click on 'Set as default directory for external terminal'.
- Then try to open the terminal window again, now it should open that directory.

![image](https://github.com/sburlyaev/IDEA-Native-Terminal-Plugin/assets/12219746/b6a558ab-312e-48d3-98a3-2fa675204f6d)

**Comment by ChrisJan00** [comment]
@sburlyaev thank you! That did the trick.

I was looking into the wrong place when searching for the relevant settings... never occurred to me that you can configure plugin settings directly from a drop-down menu in the project navigation window.

Anyway, I will close the issue. Thanks a lot :)
