### ISSUE TITLE
Paths with spaces are not working

### ISSUE THREAD

**Issue by JSteitz** [sburlyaev/IDEA-Native-Terminal-Plugin#5]
OS: macos
PHPSTORM: 2018.1
Plugin: 0.1.5

Some project paths have spaces and will not open the terminal.

**Comment by sburlyaev** [comment]
Hi @JSteitz,
I understood the issue and did some fixes but I don't have mac to test it at the moment.
I'll try to find a way to verify this.
Thanks!

**Comment by sburlyaev** [comment]
@JSteitz ,
I've fixed this. It will be available in JetBrains repository in a few days.
Thanks for your participation!
