### ISSUE TITLE
update to version 0.1.6 ,Android studio lose focus ,Can't click. 

### ISSUE THREAD

**Issue by longforus** [sburlyaev/IDEA-Native-Terminal-Plugin#6]
today i update to version 0.1.6,after the open terminal,Android studio lose focus ,Can't click. close terminal back to normal.
before update no this issue

Android Studio 3.1.3
Build #AI-173.4819257, built on June 5, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

terminal : git-bash mintty 2.8.5

**Comment by sburlyaev** [comment]
Hi @longforus ,
Can you provide your FAVORITE_TERMINAL env variable?

**Comment by longforus** [comment]
@sburlyaev  yes ,like this:
FAVORITE_TERMINAL : C:\Git\git-bash.exe

**Comment by sburlyaev** [comment]
@longforus ,
I've fixed it and uploaded a new build to the repository - waiting JetBrains approval.
Thanks!

**Comment by sburlyaev** [comment]
@longforus ,
Done! v0.1.7 is already there.

**Comment by longforus** [comment]
@sburlyaev nice! , it fixed ,i very like this plugin,very converient ,thank you for your sharing 😄.

**Comment by sburlyaev** [comment]
Thanks! You are welcome 😊
