### ISSUE TITLE
How to setup FAVORITE_TERMINAL in Mac?

### ISSUE THREAD

**Issue by vunamhung** [sburlyaev/IDEA-Native-Terminal-Plugin#7]
Hi Sergey,
I'm very like your plugin but default it work with Terminal.app, can you guide me how to setup to make it work with iTerm. I use Mac OS

Thank you.

**Comment by sburlyaev** [comment]
Hi @vunamhung ,
I'm not very familiar with macOS. Looks like it's not that easy to set env variable for all apps and users there...

**Comment by sburlyaev** [comment]
@vunamhung ,
The  main idea to pass `FAVORITE_TERMINAL=iterm` to IDE environment.
The first solution I have found it is run it from a terminal and before run IDE itself execute `export` command to set `FAVORITE_TERMINAL` variable:

$ `export FAVORITE_TERMINAL=iterm`
$ `open -a "IntelliJ IDEA Community"`

This is works for me.

**Comment by vunamhung** [comment]
Thank Sergey, your guide is work but my PHPStorm is need start from terminal. Can you build a custom version of plugin with default terminal is iTerm and send to vunamhung@gmail.com, I will appreciate you for that action.

Thank you.

**Comment by sburlyaev** [comment]
Hi @vunamhung ,
I did some more convenient thing:
In `version 0.2` you can configure the plugin directly from the **IDE Settings** menu.
The new version will be available in a few days. Thanks!

![image](https://user-images.githubusercontent.com/12219746/41832260-eee94f54-7853-11e8-80fd-6195685e791e.png)

**Comment by vunamhung** [comment]
Awsome, thank you very much.

**Comment by bescks** [comment]
When will version 0.2 be released?

**Comment by sburlyaev** [comment]
Hi @bescks ,
In a few days - waiting JetBrains approval.

**Comment by vunamhung** [comment]
Hi Sergey, I just update plugin to version 0.2, work like a charm.
Thank you.
