### ISSUE TITLE
Is there a way to setup as a default folder a subfolder in the project? 

### ISSUE THREAD

**Issue by mihailgaberov** [sburlyaev/IDEA-Native-Terminal-Plugin#8]
E.g. instead of 'C:\project, to be C:\project\web'?

**Comment by sburlyaev** [comment]
Hi @mihailgaberov ,
Unfortunately, this functionality is not implemented yet, but I will think about it in future releases.
Thanks!

**Comment by mihailgaberov** [comment]
Thanks for the quick answer!

**Comment by vunamhung** [comment]
Update to version 0.2 and you can setup it in PHPStorm setting

**Comment by sburlyaev** [comment]
Hi @mihailgaberov ,
`Version 0.2` has been released and now you can specify project sub directory in the **IDE Settings**.
Thanks!

![ntp02](https://user-images.githubusercontent.com/12219746/42017279-1ec971ee-7ab7-11e8-8741-8a68ad7298e2.png)

**Comment by mihailgaberov** [comment]
Works like a charm! Thank you guys!

**Comment by sburlyaev** [comment]
You are welcome!
